insert into public.products (
  id,
  slug,
  name,
  category,
  price,
  badge,
  description,
  detail,
  tags,
  palette,
  extra_categories,
  image,
  look,
  active
)
values
  (
    1,
    'blue-denim-shorts',
    'Blue Denim Shorts',
    'clothes',
    16,
    'New',
    'A soft blue shorts piece with a tiny waistband and stitched pocket details.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Shorts', 'Blue', 'Mixable'],
    '#5b86ac',
    array[]::text[],
    '/products/blue-denim-shorts.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#5b86ac","accent":"#5b86ac","expression":"smile"}'::jsonb,
    true
  ),
  (
    2,
    'cocoa-patch-shorts',
    'Cocoa Patch Shorts',
    'clothes',
    16,
    'New',
    'Dark cocoa shorts with sketched patch texture for cozy everyday styling.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Shorts', 'Cocoa', 'Textured'],
    '#2d1e19',
    array[]::text[],
    '/products/cocoa-patch-shorts.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#2d1e19","accent":"#2d1e19","expression":"smile"}'::jsonb,
    true
  ),
  (
    3,
    'midnight-tousle-hair',
    'Midnight Tousle Hair',
    'hair',
    18,
    'New',
    'A playful dark tousled hair piece with soft sketchy edges.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Hair', 'Tousled', 'Dark'],
    '#343340',
    array[]::text[],
    '/products/midnight-tousle-hair.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#343340","outfit":"#343340","accent":"#343340","expression":"smile"}'::jsonb,
    true
  ),
  (
    4,
    'plum-bob-hair',
    'Plum Bob Hair',
    'hair',
    18,
    'Fresh',
    'A rounded plum bob hairstyle with neat bangs and sweet side pieces.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Hair', 'Bob', 'Plum'],
    '#2c2230',
    array[]::text[],
    '/products/plum-bob-hair.png',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#2c2230","outfit":"#2c2230","accent":"#2c2230","expression":"smile"}'::jsonb,
    true
  ),
  (
    5,
    'honey-centerpart-hair',
    'Honey Centerpart Hair',
    'hair',
    18,
    'Limited',
    'A honey brown center-part hairstyle for a gentle classic plush look.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Hair', 'Honey', 'Classic'],
    '#7b623d',
    array['limited'],
    '/products/honey-centerpart-hair.png',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#7b623d","outfit":"#7b623d","accent":"#7b623d","expression":"smile"}'::jsonb,
    true
  ),
  (
    6,
    'white-comfy-shorts',
    'White Comfy Shorts',
    'clothes',
    16,
    'Fresh',
    'Clean white shorts with soft gray stitching and a relaxed plush fit.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Shorts', 'White', 'Soft'],
    '#f7f4ee',
    array[]::text[],
    '/products/white-comfy-shorts.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#f7f4ee","accent":"#f7f4ee","expression":"smile"}'::jsonb,
    true
  ),
  (
    7,
    'cream-denim-shorts',
    'Cream Denim Shorts',
    'clothes',
    16,
    'Fresh',
    'Cream denim-style shorts with a warm waistband and easy pairing color.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Shorts', 'Cream', 'Denim'],
    '#fff8e8',
    array[]::text[],
    '/products/cream-denim-shorts.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#fff8e8","accent":"#fff8e8","expression":"smile"}'::jsonb,
    true
  ),
  (
    8,
    'moss-patch-shorts',
    'Moss Patch Shorts',
    'clothes',
    16,
    'New',
    'Moss green shorts with soft shaded patches and stitched charm.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Shorts', 'Moss', 'Patch'],
    '#3f4b36',
    array[]::text[],
    '/products/moss-patch-shorts.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#3f4b36","accent":"#3f4b36","expression":"smile"}'::jsonb,
    true
  ),
  (
    9,
    'daisy-hair-clips',
    'Daisy Hair Clips',
    'accessories',
    10,
    'Tiny',
    'Two small daisy clips for adding a bright little flower moment.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Clips', 'Daisy', 'Gift add-on'],
    '#fff8dd',
    array[]::text[],
    '/products/daisy-hair-clips.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#fff8dd","accent":"#fff8dd","expression":"spark"}'::jsonb,
    true
  ),
  (
    10,
    'cocoa-beret',
    'Cocoa Beret',
    'accessories',
    18,
    'New',
    'A soft cocoa beret sitting snugly on top for a cozy, artsy plush look.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Beret', 'Cocoa', 'Hat'],
    '#3d2d22',
    array[]::text[],
    '/products/cocoa-swoop-hair.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#3d2d22","accent":"#3d2d22","expression":"spark"}'::jsonb,
    true
  ),
  (
    11,
    'blue-cozy-scarf',
    'Blue Cozy Scarf',
    'accessories',
    12,
    'Fresh',
    'A small blue scarf made for layered winter plush outfits.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Scarf', 'Blue', 'Cozy'],
    '#4f70ad',
    array[]::text[],
    '/products/blue-cozy-scarf.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#4f70ad","accent":"#4f70ad","expression":"spark"}'::jsonb,
    true
  ),
  (
    12,
    'rust-cozy-scarf',
    'Rust Cozy Scarf',
    'accessories',
    12,
    'Fresh',
    'A warm rust scarf for autumn gifts and soft outfit styling.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Scarf', 'Rust', 'Cozy'],
    '#a94732',
    array[]::text[],
    '/products/rust-cozy-scarf.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#a94732","accent":"#a94732","expression":"spark"}'::jsonb,
    true
  ),
  (
    13,
    'cream-cozy-scarf',
    'Cream Cozy Scarf',
    'accessories',
    12,
    'Fresh',
    'A cream scarf that keeps plush outfits soft and gift-ready.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Scarf', 'Cream', 'Soft'],
    '#fff8e8',
    array[]::text[],
    '/products/cream-cozy-scarf.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#fff8e8","accent":"#fff8e8","expression":"spark"}'::jsonb,
    true
  ),
  (
    14,
    'plum-centerpart-hair',
    'Plum Centerpart Hair',
    'hair',
    18,
    'Fresh',
    'A deep plum center-part hairstyle with a smooth rounded shape.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Hair', 'Plum', 'Center part'],
    '#2d2232',
    array[]::text[],
    '/products/plum-centerpart-hair.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#2d2232","outfit":"#2d2232","accent":"#2d2232","expression":"smile"}'::jsonb,
    true
  ),
  (
    15,
    'blue-studio-blazer',
    'Blue Studio Blazer',
    'clothes',
    24,
    'Fresh',
    'A tiny blue blazer with long sleeves and statement cuffs.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Blazer', 'Blue', 'Dressy'],
    '#244d6f',
    array[]::text[],
    '/products/blue-studio-blazer.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#244d6f","accent":"#244d6f","expression":"smile"}'::jsonb,
    true
  ),
  (
    16,
    'navy-button-vest',
    'Navy Button Vest',
    'clothes',
    20,
    'Fresh',
    'A navy vest with two tiny gold buttons and a neat tailored look.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Vest', 'Navy', 'Buttons'],
    '#1d3a52',
    array[]::text[],
    '/products/navy-button-vest.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#1d3a52","accent":"#1d3a52","expression":"smile"}'::jsonb,
    true
  ),
  (
    17,
    'cocoa-button-vest',
    'Cocoa Button Vest',
    'clothes',
    20,
    'Fresh',
    'A cocoa vest with warm tailoring for layered plush outfits.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Vest', 'Cocoa', 'Buttons'],
    '#704f3d',
    array[]::text[],
    '/products/cocoa-button-vest.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#704f3d","accent":"#704f3d","expression":"smile"}'::jsonb,
    true
  ),
  (
    18,
    'olive-long-coat',
    'Olive Long Coat',
    'clothes',
    26,
    'Fresh',
    'A long olive coat with cuff details for a cozy studio look.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Coat', 'Olive', 'Layer'],
    '#463f33',
    array[]::text[],
    '/products/olive-long-coat.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#463f33","accent":"#463f33","expression":"smile"}'::jsonb,
    true
  ),
  (
    19,
    'sunny-button-coat',
    'Sunny Button Coat',
    'clothes',
    26,
    'Fresh',
    'A bright yellow button coat with warm textured shading.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Coat', 'Yellow', 'Buttons'],
    '#ffbd32',
    array[]::text[],
    '/products/sunny-button-coat.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#ffbd32","accent":"#ffbd32","expression":"smile"}'::jsonb,
    true
  ),
  (
    20,
    'cream-soft-cardigan',
    'Cream Soft Cardigan',
    'clothes',
    24,
    'New',
    'A cream cardigan with long sleeves and one sweet front button.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Cardigan', 'Cream', 'Soft'],
    '#f5e3bd',
    array[]::text[],
    '/products/cream-soft-cardigan.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#f5e3bd","accent":"#f5e3bd","expression":"smile"}'::jsonb,
    true
  ),
  (
    21,
    'pink-puff-sleeves',
    'Pink Puff Sleeves',
    'clothes',
    18,
    'Tiny',
    'Pink puffy sleeves with soft ribbed cuffs for playful outfits.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Sleeves', 'Pink', 'Puffy'],
    '#efb5d7',
    array[]::text[],
    '/products/pink-puff-sleeves.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#efb5d7","accent":"#efb5d7","expression":"smile"}'::jsonb,
    true
  ),
  (
    22,
    'cocoa-soft-cardigan',
    'Cocoa Soft Cardigan',
    'clothes',
    24,
    'New',
    'A cocoa cardigan with gentle stitching and a cozy handmade feel.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Cardigan', 'Cocoa', 'Soft'],
    '#704d3c',
    array[]::text[],
    '/products/cocoa-soft-cardigan.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#704d3c","accent":"#704d3c","expression":"smile"}'::jsonb,
    true
  ),
  (
    23,
    'rust-mini-tie',
    'Rust Mini Tie',
    'accessories',
    8,
    'Tiny',
    'A tiny rust tie for polished plush portraits and gifting sets.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Tie', 'Rust', 'Mini'],
    '#b44d35',
    array[]::text[],
    '/products/rust-mini-tie.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#b44d35","accent":"#b44d35","expression":"spark"}'::jsonb,
    true
  ),
  (
    24,
    'striped-cocoa-tie',
    'Striped Cocoa Tie',
    'accessories',
    8,
    'Tiny',
    'A cocoa striped tie for a slightly fancy plush outfit.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Tie', 'Striped', 'Cocoa'],
    '#5b3528',
    array[]::text[],
    '/products/striped-cocoa-tie.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#5b3528","accent":"#5b3528","expression":"spark"}'::jsonb,
    true
  ),
  (
    25,
    'blue-mini-tie',
    'Blue Mini Tie',
    'accessories',
    8,
    'Tiny',
    'A tiny blue tie that adds a neat pop of color.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Tie', 'Blue', 'Mini'],
    '#4f70bc',
    array[]::text[],
    '/products/blue-mini-tie.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#4f70bc","accent":"#4f70bc","expression":"spark"}'::jsonb,
    true
  ),
  (
    26,
    'white-ruffle-skirt',
    'White Ruffle Skirt',
    'clothes',
    18,
    'Fresh',
    'A white ruffle skirt with soft folds and a delicate hem.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Skirt', 'White', 'Ruffle'],
    '#fbfbf7',
    array[]::text[],
    '/products/white-ruffle-skirt.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#fbfbf7","accent":"#fbfbf7","expression":"smile"}'::jsonb,
    true
  ),
  (
    27,
    'blue-flower-dress',
    'Blue Flower Dress',
    'clothes',
    24,
    'New',
    'A blue dress with a row of flower details along the hem.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Dress', 'Blue', 'Flowers'],
    '#5574b8',
    array[]::text[],
    '/products/blue-flower-dress.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#5574b8","accent":"#5574b8","expression":"smile"}'::jsonb,
    true
  ),
  (
    28,
    'yellow-scallop-dress',
    'Yellow Scallop Dress',
    'clothes',
    24,
    'New',
    'A sunny yellow dress with scalloped sleeves and hem.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Dress', 'Yellow', 'Scallop'],
    '#ffe276',
    array[]::text[],
    '/products/yellow-scallop-dress.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#ffe276","accent":"#ffe276","expression":"smile"}'::jsonb,
    true
  ),
  (
    29,
    'cream-pocket-pinafore',
    'Cream Pocket Pinafore',
    'clothes',
    22,
    'Fresh',
    'A cream pinafore with a small front pocket for tiny notes.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Pinafore', 'Cream', 'Pocket'],
    '#ead8b9',
    array[]::text[],
    '/products/cream-pocket-pinafore.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#ead8b9","accent":"#ead8b9","expression":"smile"}'::jsonb,
    true
  ),
  (
    30,
    'white-soft-tee',
    'White Soft Tee ("Your bra strap is showing!!")',
    'clothes',
    15,
    'New',
    'A clean white tee with a relaxed plush-friendly shape.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Tee', 'White', 'Everyday'],
    '#f7f7f4',
    array[]::text[],
    '/products/white-soft-tee.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#f7f7f4","accent":"#f7f7f4","expression":"smile"}'::jsonb,
    true
  ),
  (
    31,
    'black-bell-sleeve-top',
    'Black Bell Sleeve Top',
    'clothes',
    18,
    'Fresh',
    'A black top with long bell sleeves for a dramatic tiny outfit.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Top', 'Black', 'Bell sleeves'],
    '#090909',
    array[]::text[],
    '/products/black-bell-sleeve-top.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#090909","accent":"#090909","expression":"smile"}'::jsonb,
    true
  ),
  (
    32,
    'pink-sleeveless-top',
    'Pink Sleeveless Top',
    'clothes',
    15,
    'Fresh',
    'A soft pink sleeveless top for simple everyday layering.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Top', 'Pink', 'Sleeveless'],
    '#f7eef2',
    array[]::text[],
    '/products/pink-sleeveless-top.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#f7eef2","accent":"#f7eef2","expression":"smile"}'::jsonb,
    true
  ),
  (
    33,
    'black-sleeveless-top',
    'Black Sleeveless Top',
    'clothes',
    15,
    'Fresh',
    'A black sleeveless top with a clean tiny silhouette.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Top', 'Black', 'Sleeveless'],
    '#080808',
    array[]::text[],
    '/products/black-sleeveless-top.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#080808","accent":"#080808","expression":"smile"}'::jsonb,
    true
  ),
  (
    34,
    'black-short-sleeve-tee',
    'Black Short Sleeve Tee',
    'clothes',
    15,
    'Fresh',
    'A black short-sleeve tee for minimal plush outfits.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Tee', 'Black', 'Everyday'],
    '#080808',
    array[]::text[],
    '/products/black-short-sleeve-tee.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#080808","accent":"#080808","expression":"smile"}'::jsonb,
    true
  ),
  (
    35,
    'white-short-sleeve-tee',
    'White Short Sleeve Tee',
    'clothes',
    15,
    'Fresh',
    'A white short-sleeve tee with soft sketched seams.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Tee', 'White', 'Everyday'],
    '#f8f8f5',
    array[]::text[],
    '/products/white-short-sleeve-tee.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#f8f8f5","accent":"#f8f8f5","expression":"smile"}'::jsonb,
    true
  ),
  (
    36,
    'black-stitch-hem-top',
    'Black Stitch Hem Top',
    'clothes',
    18,
    'Fresh',
    'A black top with sweet white stitch details along the hem.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Top', 'Black', 'Stitched'],
    '#080808',
    array[]::text[],
    '/products/black-stitch-hem-top.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#080808","accent":"#080808","expression":"smile"}'::jsonb,
    true
  ),
  (
    37,
    'rust-collar-shirt',
    'Rust Collar Shirt',
    'clothes',
    20,
    'New',
    'A rust button-up shirt with a tiny collar and front buttons.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Shirt', 'Rust', 'Collar'],
    '#a94834',
    array[]::text[],
    '/products/rust-collar-shirt.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#a94834","accent":"#a94834","expression":"smile"}'::jsonb,
    true
  ),
  (
    38,
    'pink-bow-blouse',
    'Pink Bow Blouse',
    'clothes',
    20,
    'New',
    'A pink blouse with a soft bow and lace-like trim.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Blouse', 'Pink', 'Bow'],
    '#efbfd7',
    array[]::text[],
    '/products/pink-bow-blouse.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#efbfd7","accent":"#efbfd7","expression":"smile"}'::jsonb,
    true
  ),
  (
    39,
    'taupe-collar-shirt',
    'Taupe Collar Shirt',
    'clothes',
    20,
    'Fresh',
    'A taupe button-up shirt with simple everyday charm.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Shirt', 'Taupe', 'Collar'],
    '#a08370',
    array[]::text[],
    '/products/taupe-collar-shirt.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#a08370","accent":"#a08370","expression":"smile"}'::jsonb,
    true
  ),
  (
    40,
    'cream-collar-shirt',
    'Cream Collar Shirt',
    'clothes',
    20,
    'Fresh',
    'A cream button-up shirt with a tidy collar and soft lines.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Shirt', 'Cream', 'Collar'],
    '#fff9e8',
    array[]::text[],
    '/products/cream-collar-shirt.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#fff9e8","accent":"#fff9e8","expression":"smile"}'::jsonb,
    true
  ),
  (
    41,
    'rust-pleated-skirt',
    'Rust Pleated Skirt',
    'clothes',
    16,
    'Fresh',
    'A rust pleated skirt for warm everyday styling.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Skirt', 'Rust', 'Pleated'],
    '#a44735',
    array[]::text[],
    '/products/rust-pleated-skirt.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#a44735","accent":"#a44735","expression":"smile"}'::jsonb,
    true
  ),
  (
    42,
    'black-pleated-skirt',
    'Black Pleated Skirt',
    'clothes',
    16,
    'Fresh',
    'A black pleated skirt with a soft hand-drawn edge.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Skirt', 'Black', 'Pleated'],
    '#0a0807',
    array[]::text[],
    '/products/black-pleated-skirt.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#0a0807","accent":"#0a0807","expression":"smile"}'::jsonb,
    true
  ),
  (
    43,
    'cream-pleated-skirt',
    'Cream Pleated Skirt',
    'clothes',
    16,
    'Fresh',
    'A cream pleated skirt that pairs with almost any tiny top.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Skirt', 'Cream', 'Pleated'],
    '#fff8e9',
    array[]::text[],
    '/products/cream-pleated-skirt.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#fff8e9","accent":"#fff8e9","expression":"smile"}'::jsonb,
    true
  ),
  (
    44,
    'cream-lace-hem-skirt',
    'Cream Lace Hem Skirt',
    'clothes',
    18,
    'New',
    'A cream skirt with a soft lace-like scalloped hem.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Skirt', 'Cream', 'Lace hem'],
    '#fff8e8',
    array[]::text[],
    '/products/cream-lace-hem-skirt.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#fff8e8","accent":"#fff8e8","expression":"smile"}'::jsonb,
    true
  ),
  (
    45,
    'rust-plaid-shorts',
    'Rust Plaid Shorts',
    'clothes',
    18,
    'Fresh',
    'Rust plaid shorts with a cozy checked texture.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Shorts', 'Plaid', 'Rust'],
    '#9d4638',
    array[]::text[],
    '/products/rust-plaid-shorts.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#9d4638","accent":"#9d4638","expression":"smile"}'::jsonb,
    true
  ),
  (
    46,
    'black-comfy-shorts',
    'Black Comfy Shorts',
    'clothes',
    16,
    'Fresh',
    'Simple black shorts for easy mix-and-match styling.',
    'Hand-drawn Soolou piece made for mix-and-match plush styling.',
    array['Shorts', 'Black', 'Everyday'],
    '#080808',
    array[]::text[],
    '/products/black-comfy-shorts.jpg',
    '{"body":"#f9d8c9","belly":"#fff6ef","hair":"#4c3f4e","outfit":"#080808","accent":"#080808","expression":"smile"}'::jsonb,
    true
  ),
  (
    9001,
    'custom-base-plush',
    'Base Plush',
    'limited',
    52,
    'Base',
    'The soft Soolou plush base without clothing or accessories.',
    'A plain Soolou base plush ready to dress your way.',
    array['No clothing', 'Base plush', 'Ready to dress'],
    '#f5dcb8',
    array[]::text[],
    '/base-doll-nobg.png',
    '{"body":"#f5dcb8","belly":"#fff3df","hair":"#2c2230","outfit":"#f5dcb8","accent":"#e375ad","expression":"smile"}'::jsonb,
    true
  )
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  category = excluded.category,
  price = excluded.price,
  badge = excluded.badge,
  description = excluded.description,
  detail = excluded.detail,
  tags = excluded.tags,
  palette = excluded.palette,
  extra_categories = excluded.extra_categories,
  image = excluded.image,
  look = excluded.look,
  active = excluded.active,
  updated_at = now();
